### 목표 : 선형 모델 기반의 분류 모델 구현
- 데이터 : sklearn.datasets의 iris
- 피 처 : 2개
- 타겟 : 3개

(1) 모듈로딩 <hr>

In [92]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [93]:
# 데이터 로딩 => Bunch 타입으로 dict와 유사한 scikit-learn 클래스
#load_iris() # 전체 다 나옴

dataXy = load_iris(return_X_y=True) #데이터만 들고나옴

print(type(dataXy), len(dataXy))

<class 'tuple'> 2


In [94]:
data = load_iris()
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [95]:
# 데이터와 타겟을 DataFrame 형식으로 로딩하겠다.
dataXy = load_iris(return_X_y=True, )
#print(type(dataXy), len(dataXy), dataXy)
#print(dataXy)

In [96]:
data = load_iris(as_frame=True)
data.keys()


dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [97]:
featureDF1 = data['data']
targetDF1 = data['target']

featureDF = data['data'][:100]
targetDF = data['target'][:100]

(2) 모델 학습 진행 <hr>

In [98]:
# 모듈 로딩 
from sklearn.linear_model import LogisticRegression

In [99]:
# 모델 인스턴스 생성
model = LogisticRegression(max_iter=1000)
model.fit(featureDF, targetDF)

LogisticRegression(max_iter=1000)

In [100]:
# 학습 후 결정된 모델 파라미터 확인
print(f"classes_ : {model.classes_}")
print(f"feature_name_in_: \n{model.feature_names_in_}")
print(f"n_iter_: {model.n_iter_}")
print(f"coef_: \n{model.coef_}")
print(f"intercept_: \n{model.intercept_}")



# featureDF1 = data['data']      targetDF1 = data['target'] 일때
# 피쳐가 4개이다
# coef가 12개, intercept가 3개로 나온 이유 => 타겟이 3종류니까 
    # coef_: 
    # [[-0.42364806  0.96739434 -2.51708319 -1.07937296]
    #    ㄴ  y = -0.4 * f1 + 0.96 * f2 + -2.5 * f3 + -1.07 * f4  이런식으로 predict가 진행될것
    #  [ 0.53447765 -0.3216458  -0.20639707 -0.94423775]
    #  [-0.11082959 -0.64574854  2.72348026  2.02361071]]
    # intercept_: 
    # [  9.84997373   2.23721656 -12.08719029]


# featureDF = data['data'][:100]    targetDF = data['target'][:100] 일떄
# coef가 4개, interceptr가 1개 나온 이유 => 타겟이 2종류이지만, 한개가 무엇인지만 알면 나머지는 자연스레 알수있으니까

classes_ : [0 1]
feature_name_in_: 
['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
n_iter_: [23]
coef_: 
[[ 0.44036482 -0.90696813  2.30849566  0.96232763]]
intercept_: 
[-6.61165119]


[OvA/OvR] ===> 3개 모델
setosa      : setosa vs 나머지
Versicolor  : Versicolor vs 나머지
virginica   : virginica vs 나머지

[OvO] ==> (3*2)/2 = 3개
Setosa vs versicolor 
setosa vs virginica
versicolor vs virginica

In [101]:
model.score(featureDF, targetDF)

1.0

In [102]:
featureDF.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2

In [103]:
model.predict(featureDF.iloc[[0]])

# 제일 첫번째 행을 넣어봄
# 2차원을 만들어주어야 해서 iloc[[0]]
# 결과가 0번이다

array([0])

In [104]:
model.predict(featureDF.iloc[[-1]])

# 제일 마지막 행을 넣어봄
# 2차원을 만들어주어야 해서 iloc[[-1]]
# 결과가 2번이다

array([1])

In [105]:
targetDF

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int32

In [106]:
# 각 분류 클래스에 대한 확률값
np.round(model.predict_proba(featureDF.iloc[[-1]]), 3)

array([[0.017, 0.983]])

In [107]:
# 각 분류기의 선형식에서 계산한 값
model.decision_function(featureDF.iloc[[-1]])

array([4.07477562])