### 교차 검증
- 부족한 데이터 셋 및 특정 데이터에 과대적합 되는 문제 해결하기 위한 방안
- 학습 데이터셋을 일정 크기의 데이터로 n개 분리 후 1/n은 검증용, 나머지는 학습용으로 사용

[1] 모듈 로딩 및 데이터 준비 <hr>

In [362]:
import numpy as np
from sklearn.model_selection import KFold

X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4])

In [363]:
# Kfold 인스턴스 생성 => 데이터를 2개로 분할해주는 객체
k_fold = KFold(n_splits=2)      #4개뿐이라 2개까지만 쪼개기 가능

In [364]:
# 데이터 분할 
datasets = k_fold.split(X)

for dataset in datasets:
    print(dataset)

(array([2, 3]), array([0, 1]))
(array([0, 1]), array([2, 3]))


In [365]:
datasets

<generator object _BaseKFold.split at 0x0000014AFA95B2E0>

In [366]:
### perch.csv 파일 데이터 기본 5등분
import pandas as pd

perchDF = pd.read_csv('../data/perch3.csv')
perchDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Weight  56 non-null     float64
 1   Length  56 non-null     float64
 2   Height  56 non-null     float64
 3   Width   56 non-null     float64
dtypes: float64(4)
memory usage: 1.9 KB


In [367]:
# perchDF => 5등분
fold_5 = KFold()
datasets = fold_5.split(perchDF)

for index, dataset in enumerate(datasets):
    print(f"{index} => {dataset}")
    #print(dataset)
    print(len(dataset))
    # 앞에 나오는게 train이고 뒤에 나오는게 test
    print('-'*40)

0 => (array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]))
2
----------------------------------------
1 => (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]), array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]))
2
----------------------------------------
2 => (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]), array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]))
2
----------------------------------------
3 => (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
    

In [368]:
# perchDF => 3등분
fold_5 = KFold(n_splits=3)
datasets = fold_5.split(perchDF)

for index, (train, test) in enumerate(datasets):
    print(f"{index} => {train.shape}   {test.shape}")


# return 값 해설
# 56개를 3등분해서 1개는 테스트용 (18 ~ 19 개)
# 그러면 테스트용 버전이 3가지가 되어야 하니까 총 3개

0 => (37,)   (19,)
1 => (37,)   (19,)
2 => (38,)   (18,)


In [369]:
# perchDF => 3등분
fold_5 = KFold(n_splits=3)
datasets = fold_5.split(perchDF)

for index, (train, test) in enumerate(datasets):
    print(f"{index}")
    print(train)
    print(test)

# return값 해설
# 숫자들은 모두 인덱스 번호에 해당함

0
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48 49 50 51 52 53 54 55]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 38 39 40 41 42
 43 44 45 46 47 48 49 50 51 52 53 54 55]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
[38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [370]:
# perchDF => 5등분
fold_5 = KFold()
datasets = fold_5.split(perchDF)

for index, (train, test) in enumerate(datasets):
    print(f"{index} => {train.shape}   {test.shape}")

# return 값 해설
# 56개를 5등분해서 1개는 테스트용 (11 ~ 12 개)
# 그러면 테스트용 버전이 5가지가 되어야 하니까 총 5개

0 => (44,)   (12,)
1 => (45,)   (11,)
2 => (45,)   (11,)
3 => (45,)   (11,)
4 => (45,)   (11,)


In [371]:
## 타겟이 분류인 경우

irisDF = pd.read_csv('../data/iris.csv', header = None)
irisDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
 4   4       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [372]:
irisDF = irisDF.replace('Iris-setosa', 0)
irisDF = irisDF.replace('Iris-virginica', 1)
irisDF = irisDF.replace('Iris-versicolor',2)

irisDF[4].value_counts()


4
0    50
2    50
1    50
Name: count, dtype: int64

In [373]:
k_fold = KFold(n_splits=3, shuffle=True)
ret = k_fold.split(irisDF[irisDF.columns[:-1]])

In [374]:
for idx, (train, test) in enumerate(ret):
    print(idx, train, test, sep ='\n')
    print('-'*50)
    
# shuffle = False 일때 ==> 지금 섞여있는 상태가 아닌 거라서 variety 종류가 몰려있다. (test의 인덱스 번호 참고)
# shuffle = True  일떼 ==> 섞여있는 상태라는 것을 확인할 수 있다.

0
[  2   3   4   5   6   7   9  11  15  18  20  21  22  24  25  27  28  30
  31  33  34  35  36  38  40  41  44  46  49  50  53  54  55  56  57  58
  59  61  62  64  65  66  68  71  72  74  76  77  80  81  82  84  85  86
  88  89  90  91  92  93  96  99 100 101 103 104 106 109 110 111 112 113
 114 115 116 118 119 120 122 124 127 129 130 131 132 133 134 135 137 138
 139 140 141 142 143 144 146 147 148 149]
[  0   1   8  10  12  13  14  16  17  19  23  26  29  32  37  39  42  43
  45  47  48  51  52  60  63  67  69  70  73  75  78  79  83  87  94  95
  97  98 102 105 107 108 117 121 123 125 126 128 136 145]
--------------------------------------------------
1
[  0   1   2   3   4   6   8  10  12  13  14  15  16  17  19  20  23  25
  26  29  30  32  36  37  39  40  42  43  44  45  46  47  48  50  51  52
  53  55  56  58  59  60  61  63  64  66  67  68  69  70  71  72  73  75
  76  77  78  79  82  83  85  87  88  89  90  91  92  94  95  96  97  98
 102 103 105 106 107 108 111 112 113 115 1

In [375]:
k_fold = KFold(n_splits=3, shuffle=True)
ret = k_fold.split(irisDF[irisDF.columns[:-1]])

for idx, (train, test) in enumerate(ret):
    train_list = train.tolist()        #ndarray로 나오기 때문에 리스트로 변환해주어야 함
    
    result_df = irisDF[4][train_list]
    #print(result_df)
    value_df = result_df.value_counts()
    print(f' = = = = = = = {idx} = = = = = = = ')
    print(value_df)
    print( )
    
    
    
# shuffle을 했을때 균일하게 분포되어있는지 확인해보았다.
# 해당 인덱스를 뽑아서 데이터 프레임을 만든 후 value_counts() 해보았다. 
# 그랬더니 고르게 분포된 것임을 확인함!

 = = = = = = = 0 = = = = = = = 
4
1    37
0    34
2    29
Name: count, dtype: int64

 = = = = = = = 1 = = = = = = = 
4
0    37
2    37
1    26
Name: count, dtype: int64

 = = = = = = = 2 = = = = = = = 
4
1    37
2    34
0    29
Name: count, dtype: int64


In [376]:
from sklearn.linear_model import LogisticRegression

k_fold = KFold(n_splits=3, shuffle=True)
ret = k_fold.split(irisDF[irisDF.columns[:-1]])

train_score3= []
test_score3 = []

total_df = pd.DataFrame()

for idx, (train, test) in enumerate(ret):
    # 학습용, 테스트용 인덱스 반환
    train_idx = train.tolist()
    test_idx = test.tolist()
    
    # 인덱스에 해당하는 데이터 셋 추출
    trainDF = irisDF.iloc[train_idx]
    testDF = irisDF.iloc[test_idx]
    #print(trainDF[4].value_counts()/trainDF.shape[0])
    #print(testDF[4].value_counts()/testDF.shape[0])
    
    X_train = trainDF[trainDF.columns[:4]]
    y_train = trainDF[trainDF.columns[4]]
    
    X_test = testDF[testDF.columns[:4]]
    y_test = testDF[testDF.columns[4]]

    # 분류모델 학습
    log_model = LogisticRegression(max_iter=1000, solver = 'liblinear')
    log_model.fit(X_train, y_train)
    
    # 훈련 및 검증용 성능
    train_score = log_model.score(X_train, y_train)
    test_score = log_model.score(X_test, y_test)
    print(f"= = = = = = = = = = = = = = [ {idx} ] = = = = = = = = = = = = = = ")
    print(f"     train score : {train_score}          test score : {test_score}")
    print()
    train_score3.append(train_score)
    test_score3.append(test_score)

total_df['train_score'] = train_score3
total_df['test_score'] = test_score3
total_df['model'] = 'logistic regression'
    
# 최종 점수를 구하기 위해 평균을 구하기 위해 각 점수를 리스트에 담았다.

= = = = = = = = = = = = = = [ 0 ] = = = = = = = = = = = = = = 
     train score : 0.97          test score : 0.94

= = = = = = = = = = = = = = [ 1 ] = = = = = = = = = = = = = = 
     train score : 0.93          test score : 0.94

= = = = = = = = = = = = = = [ 2 ] = = = = = = = = = = = = = = 
     train score : 0.97          test score : 0.96


In [377]:
total_df

train_score  test_score                model
0         0.97        0.94  logistic regression
1         0.93        0.94  logistic regression
2         0.97        0.96  logistic regression

In [378]:
print(f"train score 평균 {sum(train_score3)/3}")
print(f"test score 평균  {sum(test_score3)/3}")

# 평균을 내서 최종 성적으로 결론짓는다!

train score 평균 0.9566666666666667
test score 평균  0.9466666666666667
